名称：微信
在：
  workflow_dispatch：
  时间表：
    # 代表国际标准时间4点0分，北京时间需要+8小时，代表北京时间中午12点运行
    - 克朗： '0 22 * * *'
招聘职位：
#将工作流程中运行的所有作业组合在一起
  构建：
  #定义名为 build 的作业。子键将定义作业的属性
    run-on： ubuntu-latest
    步骤：
      - 用途：操作/checkout@v2
    
      - 名称： 设置蟒蛇 3.9
        用途：操作/设置python@v2
        与：
          蟒蛇版：3.9.1
      - 名称： 安装点包
        运行： |
蟒蛇 -m 点安装 --升级点
pip3 安装 -r 要求.txt
      - 名称：微信
        运行： |
蟒蛇3 main.py
